import { addDays, todayLA } from '../shared/dates';
import { GOAL_START } from '../shared/config';
import type { Deal, Snapshot } from '../shared/types';

/**
 * Sample data for the shareable demo build. Mirrors scripts/seed.ts so what you
 * click through here is what the real app looks like after `npm run seed`.
 *
 * Dates are anchored to the sprint start rather than to "today" so the numbers
 * stay inside the goal window and actually count toward the $3,000.
 */

const today = todayLA();
const d = (n: number) => addDays(GOAL_START, n);

/** Sprint days that have already happened, capped at today. */
const elapsed = [d(0), d(1), d(2)].filter((x) => x <= today);
const [day1 = today, day2 = today, day3 = today] = elapsed;

export function demoSnapshot(): Snapshot {
  const deals: Deal[] = [
    {
      id: 'demo-1',
      business_name: 'Sunrise Plumbing',
      contact_name: 'Marco Reyes',
      phone: '619-555-0142',
      source: 'Cold call',
      owner: 'Ryan',
      stage: 'In Build',
      deposit_amount: 250,
      deposit_date: day1,
      balance_amount: 250,
      balance_date: '',
      delivery_hours: 0,
      date_created: addDays(day1, -5),
      last_touch: day2,
      next_action: 'Send draft site for review',
      next_action_date: today,
      notes: 'Wants booking widget on the homepage.',
    },
    {
      id: 'demo-2',
      business_name: 'Coastal Electric',
      contact_name: 'Dana Whitfield',
      phone: '619-555-0188',
      source: 'Referral',
      owner: 'Ryan',
      stage: 'Deposit Paid',
      deposit_amount: 250,
      deposit_date: day2,
      balance_amount: 0,
      balance_date: '',
      delivery_hours: 0,
      date_created: addDays(day1, -3),
      last_touch: today,
      next_action: 'Kickoff call',
      next_action_date: addDays(today, 1),
      notes: '',
    },
    {
      id: 'demo-3',
      business_name: 'Harbor HVAC',
      contact_name: 'Luis Ortega',
      phone: '619-555-0117',
      source: 'Cold call',
      owner: 'Darius',
      stage: 'Booked',
      deposit_amount: 0,
      deposit_date: '',
      balance_amount: 0,
      balance_date: '',
      delivery_hours: 0,
      date_created: addDays(day1, -2),
      last_touch: day2,
      next_action: 'Strategy call',
      next_action_date: addDays(today, 2),
      notes: '',
    },
    {
      id: 'demo-4',
      business_name: 'Mesa Roofing Co',
      contact_name: 'Tina Alvarez',
      phone: '619-555-0163',
      source: 'Apollo',
      owner: 'Darius',
      stage: 'Conversation',
      deposit_amount: 0,
      deposit_date: '',
      balance_amount: 0,
      balance_date: '',
      delivery_hours: 0,
      date_created: addDays(today, -9),
      // Deliberately stale + overdue so both amber flags are visible.
      last_touch: addDays(today, -7),
      next_action: 'Second call attempt',
      next_action_date: addDays(today, -2),
      notes: '',
    },
    {
      id: 'demo-5',
      business_name: 'Pacific Pest Control',
      contact_name: 'Grant Meyer',
      phone: '619-555-0134',
      source: 'Cold call',
      owner: 'Darius',
      stage: 'Balance Paid',
      deposit_amount: 250,
      deposit_date: addDays(today, -12),
      balance_amount: 250,
      balance_date: addDays(today, -5),
      // $500 / 7h = $71/hr, comfortably above the $60 floor.
      delivery_hours: 7,
      date_created: addDays(today, -15),
      last_touch: addDays(today, -5),
      next_action: 'Pitch the monthly retainer',
      next_action_date: addDays(today, 3),
      notes: 'Happy with the site. Retainer conversation open.',
    },
    {
      id: 'demo-6',
      business_name: 'Kearny Garage Doors',
      contact_name: 'Phil Nakamura',
      phone: '619-555-0179',
      source: 'Cold call',
      owner: 'Ryan',
      stage: 'Dead',
      deposit_amount: 0,
      deposit_date: '',
      balance_amount: 0,
      balance_date: '',
      delivery_hours: 0,
      date_created: addDays(today, -10),
      last_touch: addDays(today, -8),
      next_action: '',
      next_action_date: '',
      notes: 'Dead: has a nephew who "does websites".',
    },
  ];

  return {
    daily_log: [
      {
        date: day1,
        person: 'Darius',
        touches: 28,
        conversations: 4,
        booked_calls: 1,
        deposits_closed: 0,
        cash_collected: 0,
        build_task_done: true,
        blocker: '',
        note: 'Reworked the roofer script, better hook.',
      },
      {
        date: day1,
        person: 'Ryan',
        touches: 31,
        conversations: 5,
        booked_calls: 2,
        deposits_closed: 1,
        cash_collected: 250,
        build_task_done: false,
        blocker: '',
        note: 'Sunrise Plumbing paid the deposit on the call.',
      },
      {
        date: day2,
        person: 'Darius',
        touches: 22,
        conversations: 3,
        booked_calls: 0,
        deposits_closed: 0,
        cash_collected: 0,
        build_task_done: true,
        blocker: 'Waiting on logo files from Sunrise.',
        note: '',
      },
      {
        date: day2,
        person: 'Ryan',
        touches: 26,
        conversations: 6,
        booked_calls: 1,
        deposits_closed: 1,
        cash_collected: 250,
        build_task_done: false,
        blocker: '',
        note: 'Coastal Electric deposit. Balance due on delivery.',
      },
      {
        date: day3,
        person: 'Darius',
        touches: 12,
        conversations: 2,
        booked_calls: 0,
        deposits_closed: 0,
        cash_collected: 0,
        build_task_done: false,
        blocker: '',
        note: '',
      },
      {
        date: day3,
        person: 'Ryan',
        touches: 18,
        conversations: 3,
        booked_calls: 1,
        deposits_closed: 0,
        cash_collected: 250,
        build_task_done: false,
        blocker: 'Two prospects want to see a live example first.',
        note: '',
      },
    ],
    deals,
    standups: [
      {
        date: today,
        person: 'Ryan',
        yesterday: '26 dials, closed the Coastal Electric deposit.',
        today: 'Follow up the 4 warm ones, book 2 calls.',
        blocker: 'Two prospects want to see a live example first.',
        submitted_at: new Date(Date.now() - 90 * 60_000).toISOString(),
      },
    ],
    weekly_review: [],
    fetched_at: new Date().toISOString(),
  };
}
